# Generated by Django 5.1.3 on 2025-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpro',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
