# Generated by Django 5.1.3 on 2025-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0004_alter_jobapplication_unique_together_userpro_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
