# Generated by Django 5.1.3 on 2025-07-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0005_networkconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkconnection',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='networkconnection',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='networkconnection',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AlterField(
            model_name='networkconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
