# Generated by Django 5.1.3 on 2025-05-12 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0006_jobapplications_delete_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplications',
            new_name='JobApplication',
        ),
    ]
