# Generated by Django 5.1.3 on 2025-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0007_rename_jobapplications_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
