# Generated by Django 5.1.3 on 2025-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0009_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
