# Generated by Django 5.1.3 on 2025-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0011_trainingcourse_category_trainingcourse_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='category',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Business', 'Business'), ('Design', 'Design'), ('Marketing', 'Marketing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50, null=True),
        ),
    ]
