# Generated by Django 5.1.3 on 2025-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0011_message_file_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
