# Generated by Django 5.1.3 on 2025-05-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0012_alter_trainingcourse_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='enrollment_count',
        ),
    ]
