# Generated by Django 5.1.3 on 2025-07-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0012_message_is_audio_message_is_image_message_is_video'),
    ]

    operations = [
    ]
