# Generated by Django 5.1.3 on 2025-05-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0013_remove_trainingcourse_enrollment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
