# Generated by Django 5.1.3 on 2025-07-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthApp', '0014_enrollment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
